services:
  privcloud-sharing:
    image: simthem/privcloud-sharing:latest
    container_name: privcloud-sharing
    # build:
    #   context: .
    #   args:
    #     # Uncomment and set if building behind a proxy
    #     # HTTP_PROXY: http://your-proxy:3128
    #     # HTTPS_PROXY: http://your-proxy:3128

    restart: unless-stopped
    ports:
      - "3000:3000"
    # environment:
      # - TRUST_PROXY=true # Set to true if a reverse proxy is in front of the container

      # -- Proxy (uncomment and set if your server accesses the internet through a proxy) --
      # - NODE_OPTIONS=--dns-result-order=ipv4first --require /opt/app/backend/node_modules/global-agent/bootstrap
      # - GLOBAL_AGENT_HTTP_PROXY=http://your-proxy:3128
      # - GLOBAL_AGENT_NO_PROXY=localhost,127.0.0.1,::1
      # - HTTP_PROXY=http://your-proxy:3128
      # - HTTPS_PROXY=http://your-proxy:3128
      # - NO_PROXY=localhost,127.0.0.1,::1
    volumes:
      - "./data:/opt/app/backend/data"
      - "./data/images:/opt/app/frontend/public/img"
